title: Breakthrough Innovations Project Data Analytics
description: Thank you for visiting our Innovations Project page. This website provides information about our research on data visualization, statistical modeling, and policies.
sitename: Breakthrough Innovations Project Data Analytics
baseurl: '/visalization-web01'

sass:
  sass_dir: /assets/_sass
  style: :compressed

collections:
  features:
    output: true
    permalink: /feature/:path/

models:
    output: true
    permalink: /models/
policies:
    output: true
    permalink: /policies/

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME

